
version: "3"

services:
   php:
      build: ./php
      depends_on:
         - sql
      env_file:
         - ./docker-compose-lesson.env
   ng:
      build: ./ng
      depends_on:
         - php
      ports:
         - 80:80
   sql:
      build: ./sql
      env_file:
         - ./docker-compose-lesson.env