
version: "3"

services:
   backend:
      build: ./php
      depends_on:
         - sql
      env_file:
         - ./docker-compose-lesson.env
      environment:
         - MYSQL_HOST=mysql
   ng:
      build: ./ng
      depends_on:
         - backend
      ports:
         - 80:80
   sql:
      build: ./sql
      env_file:
         - ./docker-compose-lesson.env
      ports: